### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by BotyE** [jloro/AmongUsMods#1]
The mod does not work, installed as in the guide. Other Sherif-type mods work, but yours don't.

**Comment by jloro** [comment]
Are you using the itch version and not the Steam one ?

**Comment by BotyE** [comment]
I use steam version 12.9. But as far as I understand, your mod is for version 11.17, but this is not specified anywhere.

> Are you using the itch version and not the Steam one ?

**Comment by jloro** [comment]
It's specified at the top of the readme:
`WARNING THIS IS FOR ITCH VERSION 2020.11.17`.
